apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: glueops-instrumentation
  namespace: glueops-core
spec:
  exporter:
    endpoint: http://otel-collector-collector.glueops-core-otel.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_always_on


   