apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: glueops-core-otel
spec:
  config: |
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
      exporters:
        otlphttp/loki:
          logs_endpoint: http://loki-write-headless.glueops-core-loki:3100/otlp/v1/logs
          headers:
            "X-Scope-OrgID": "nonprod.gliese667cc.onglueops.rocks"
        otlphttp/trace:
          traces_endpoint: http://grafana-tempo-distributor.glueops-core-tempo:4318/v1/traces
          headers:
            "X-Scope-OrgID": "nonprod.gliese667cc.onglueops.rocks"
        prometheusremotewrite:
          endpoint: http://kps-prometheus.glueops-core-kube-prometheus-stack:9090/api/v1/write
          target_info:
            enabled: true 
      connectors:
        spanmetrics:
          namespace: span.metrics    
          dimensions:
            - name: http.method
              default: GET
            - name: http.status_code
            - name: http.target
            - name: net.peer.ip
          exemplars:
            enabled: true
          dimensions_cache_size: 1000
          aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"    
          metrics_flush_interval: 15s
          metrics_expiration: 5m 
          resource_metrics_key_attributes:
            - service.name
            - telemetry.sdk.language
            - telemetry.sdk.name 
         
      service:
        telemetry:
          metrics:
            address: 0.0.0.0:8888
        pipelines:
          traces:
            receivers: [otlp]
            processors: []
            exporters: [otlphttp/trace, spanmetrics]
          metrics:
            receivers: [spanmetrics]   #otlp -> spanmetrics. # Connector 'spanmetrics' should be used as an exporter and receiver in the pipeline.
            processors: []
            exporters: [prometheusremotewrite]
          logs:
            receivers: [otlp]
            processors: []
            exporters: [otlphttp/loki]
          
              

