apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: glueops-core-otel
spec:
  config: |
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
      exporters:
        otlphttp/loki:
          headers:
            X-Scope-OrgID: nonprod.gliese667cc.onglueops.rocks
          logs_endpoint: http://loki-write-headless.glueops-core-loki:3100/otlp/v1/logs
        otlphttp/trace:
          headers:
            X-Scope-OrgID: nonprod.gliese667cc.onglueops.rocks
          traces_endpoint: http://grafana-tempo-distributor.glueops-core-tempo:4318/v1/traces
        prometheusremotewrite:
          endpoint: http://kps-prometheus.glueops-core-kube-prometheus-stack:9090/api/v1/write
          target_info:
            enabled: true
      connectors:
        spanmetrics:
          aggregation_temporality: AGGREGATION_TEMPORALITY_CUMULATIVE
          dimensions:
            - default: GET
              name: http.method
            - name: http.status_code
            - name: http.target
            - name: net.peer.ip
          dimensions_cache_size: 1000
          exemplars:
            enabled: true
          metrics_expiration: 5m
          metrics_flush_interval: 15s
          namespace: span.metrics
          resource_metrics_key_attributes:
            - service.name
            - telemetry.sdk.language
            - telemetry.sdk.name
      service:
        telemetry:
          metrics:
            address: 0.0.0.0:8888
        pipelines:
          logs:
            exporters:
              - otlphttp/loki
            receivers:
              - otlp
          metrics:
            exporters:
              - prometheusremotewrite
            receivers:
              - spanmetrics
          traces:
            exporters:
              - otlphttp/trace
              - spanmetrics
            receivers:
              - otlp
