apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: glueops-core-otel
spec:
  config: |
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
      exporters:
        otlphttp/loki:
          headers:
            X-Scope-OrgID: nonprod.gliese667cc.onglueops.rocks
          logs_endpoint: http://loki-write-headless.glueops-core-loki:3100/otlp/v1/logs
        otlphttp/trace:
          headers:
            X-Scope-OrgID: nonprod.gliese667cc.onglueops.rocks
          traces_endpoint: http://grafana-tempo-distributor.glueops-core-tempo:4318/v1/traces
      processors:
        batch:
          send_batch_size: 10000
          timeout: 10s
        memory_limiter:
          check_interval: 1s
          limit_percentage: 75
          spike_limit_percentage: 15
      service:
        telemetry:
          metrics:
            address: 0.0.0.0:8888
        pipelines:
          logs:
            exporters:
              - otlphttp/loki
            processors:
              - memory_limiter
              - batch
            receivers:
              - otlp
          traces:
            exporters:
              - otlphttp/trace
            processors:
              - memory_limiter
              - batch
            receivers:
              - otlp
