apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-tempo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core-tempo
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: tempo-distributed
    targetRevision: 1.16.2
    helm:
      skipCrds: true
      values: |-
        compactor:
          config:
            compaction:
             block_retention: {{ .Values.tempo.compaction_block_retention}}
        gateway:
          enabled: true
        ingester:  
          config:
            flush_check_period: 10s
            flush_all_on_shutdown: true
            complete_block_timeout: 1m
            max_block_bytes: 524288000
            trace_idle_period: 10s
        server:
            grpc_server_max_recv_msg_size: 81194305
            grpc_server_max_send_msg_size: 81194305
        storage:
          trace: 
          {{- toYaml .Values.tempo.storage | nindent 12 }}
        traces:
          otlp:
            http:
              enabled: true
            grpc:
              enabled: true
              max_recv_msg_size_mib: 8194305
        metricsGenerator:
          enabled: true
          replicas: 2
          resources: 
            requests:
                cpu: 250m
                memory: 512Mi  # Minimum request
            limits:
                cpu: 1024m
                memory: 2Gi 
          processor:
            overrides:
              "single-tenant":
                metrics_generator_processors:
                  - span-metrics
                  - service-graphs
          config:
            metric_generator:
              batch_size: 1000
              concurrent_workers: 4
              window_size: 5m
            processor:
              service_graphs:
                dimensions: ["http.method","http.status_code","http.target","service.name","net.peer.ip"]
                histogram_buckets: [0.1, 0.2, 0.4, 0.8, 1.6, 3.2, 6.4, 12.8]
                max_items: 1000
                wait: 10s
                workers: 4
              span_metrics:
                dimensions: ["http.method","http.status_code","http.target","service.name","net.peer.ip"]
                histogram_buckets: [0.002, 0.004, 0.008, 0.016, 0.032, 0.064, 0.128, 0.256, 0.512, 1.02, 2.05, 4.10]

            storage:
              remote_write: 
              - url: http://kps-prometheus.glueops-core-kube-prometheus-stack:9090/api/v1/write
        global_overrides:
          defaults:
            metrics_generator:
              processors:
                - service-graphs
                - span-metrics
                    

        
