apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glueops-pomerium-post-deploy
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: pomerium
  project: glueops-core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
  source:
    repoURL: 'https://github.com/GlueOps/platform-helm-chart-pomerium-post-deploy'
    path: .
    targetRevision: v0.4.1
    helm:
      skipCrds: true
      parameters:
        - name: dex_domain
          value: dex.{{ .Values.captain_domain }}
        - name: pomerium_domain
          value: authenticated.{{ .Values.captain_domain }}
        - name: ingress_cert_name
          value: {{ .Values.certManager.name_of_default_certificate }}
        - name: client_id
          value: pomerium
        - name: client_secret
          value: {{ .Values.dex.pomerium.client_secret }}
        - name: enable_proxy_protocol
          value: "{{ .Values.enable_chisel_proxy_protocol }}"
