apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glueops-network-exporter
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core-network-exporter
  project: glueops-core
  syncPolicy:
    syncOptions:
      - Replace=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
      limit: 2
  source:
    repoURL: 'https://incubating-helm.gpkg.io/platform'
    chart: glueops-network-exporter
    targetRevision: 0.1.0-alpha1
