apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: captain-repo-manifests
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core
  project: glueops-core
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: manifests/
    repoURL: {{ .Values.captain_repo.ssh_clone_url }}
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    syncOptions:
    - CreateNamespace=true
---
apiVersion: v1
data:
  insecure: dHJ1ZQ== # true
  name: Y2FwdGFpbi1yZXBvLW1hbmlmZXN0cwo= # captain-repo-manifests
  project: Z2x1ZW9wcy1jb3Jl # glueops-core
  type: Z2l0 # git
  url: {{ .Values.captain_repo.ssh_clone_url | b64enc }}
  sshPrivateKey: {{ .Values.captain_repo.private_b64enc_deploy_key }}
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-captain-manifests
