apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core-keda
  source:
    repoURL: 'https://kedacore.github.io/charts'
    targetRevision: 2.10.2
    chart: keda
    helm:
      values: |-
        resources:
          operator:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1
              memory: 1000Mi
        prometheus:
          metricServer:
            enabled: true
            serviceMonitor:
              enabled: true
          operator:
            enabled: true
            port: 8080
            serviceMonitor:
              enabled: true
            # prometheusRules:
            #   enabled: true
            #   namespace: glueops-core-keda
            #   alerts:
            #     - alert: KedaScalerErrors
            #       annotations:
            #         description: Keda scaledObject {{ $labels.scaledObject }} is experiencing errors with {{ $labels.scaler }} scaler
            #         summary: Keda Scaler {{ $labels.scaler }} Errors
            #       expr: sum by ( scaledObject , scaler) (rate(keda_metrics_adapter_scaler_errors[2m]))  > 0
            #       for: 2m
            #       labels:
            #         severity: warning
            #     - alert: '[Keda] Errors in Scaled Object'
            #       expr: |
            #         rate(keda_metrics_adapter_scaled_object_errors[5m])> 0
            #       for: 10m
            #       labels:
            #         severity: warning
            #       annotations:
            #         description: Errors detected in scaled object
          webhooks:
            enabled: true
            port: 8080
            serviceMonitor:
              enabled: true
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
