apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glueops-operator-waf-web-acl
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core-operators
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
      limit: 2
  source:
    repoURL: https://helm.gpkg.io/project-template
    chart: app
    targetRevision: 0.4.0
    helm:
      values: |
        appName: 'glueops-operator-waf-web-acl'
        image:
          registry: ghcr.io
          repository: glueops/metacontroller-operator-waf-web-acl
          tag: v0.3.2
          port: 8000

        service:
          enabled: true
          port: 80

        app:
          port: 8000
        deployment:
          envVariables:
            - name: AWS_ACCESS_KEY_ID
              value: "{{ .Values.glueops_operators.web_acl.aws_accessKey }}"
            - name: AWS_SECRET_ACCESS_KEY
              value: "{{ .Values.glueops_operators.web_acl.aws_secretKey }}"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: CAPTAIN_DOMAIN
              value: "{{ .Values.captain_domain }}"
            - name: LOG_LEVEL
              value: "INFO"
              
          {{- toYaml .Values.glueops_node_and_tolerations | nindent 10 }}
          replicas: 2
          enabled: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi


        customResources:
          - |-
            apiVersion: apiextensions.k8s.io/v1
            kind: CustomResourceDefinition
            metadata:
              name: webapplicationfirewallwebacls.metacontroller.glueops.dev
            spec:
              group: metacontroller.glueops.dev
              names:
                kind: WebApplicationFirewallWebACL
                plural: webapplicationfirewallwebacls
                singular: webapplicationfirewallwebacl
                shortNames:
                - webacl
                - webacls
                - wafwebacl
                - wafwebacls
              scope: Namespaced
              versions:
              - name: v1alpha1
                served: true
                storage: true
                schema:
                  openAPIV3Schema:
                    type: object
                    properties:
                      status:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      spec:
                        type: object
                        properties:
                          web_acl_definition:
                            type: string
                            description: "Raw JSON string representation of the full AWS WAF WebACL definition"
                subresources:
                  status: {}
          - |-
            apiVersion: metacontroller.k8s.io/v1alpha1
            kind: CompositeController
            metadata:
              name: glueops-operator-waf-web-acl
            spec:
              generateSelector: true
              parentResource:
                apiVersion: metacontroller.glueops.dev/v1alpha1
                resource: webapplicationfirewallwebacls
              childResources:
                - apiVersion: v1
                  resource: configmaps
                  updateStrategy:
                    method: InPlace
              resyncPeriodSeconds: 30
              hooks:
                sync:
                  webhook:
                    url: http://glueops-operator-waf-web-acl.glueops-core-operators.svc.cluster.local/sync
                    timeout: "60s"
                finalize:
                  webhook:
                    url: http://glueops-operator-waf-web-acl.glueops-core-operators.svc.cluster.local/finalize
                    timeout: "60s"
        


                    