apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-alert-group-controller
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core-loki-alert-group-controller
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
      limit: 2
  source:
    repoURL: 'https://helm.gpkg.io/platform'
    chart: glueops-metacontroller-operator-loki-rule-group
    targetRevision: 0.3.1
    helm:
      parameters:
        - name: image.lokiApiEndpoint
          value: 'http://loki-gateway.glueops-core-loki.svc.cluster.local'
