apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-servicemonitors
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 60s
        maxDuration: 3m0s
        factor: 2
      limit: 10
  source:
    repoURL: https://helm.gpkg.io/project-template
    chart: app
    targetRevision: 0.8.1
    helm:
      values: |
        appName: '{{ .Release.Name }}'
        
        # https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-application-controller/servicemonitor.yaml
        # https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-applicationset/servicemonitor.yaml
        # https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-notifications/servicemonitor.yaml
        # https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-repo-server/servicemonitor.yaml
        # https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-server/servicemonitor.yaml

        customResources:
          - |-
            apiVersion: monitoring.coreos.com/v1
            kind: ServiceMonitor
            metadata:
              name: argocd-application-controller
            spec:
              endpoints:
                - port: http-metrics
                  interval: 30s
                  path: /metrics
              namespaceSelector:
                matchNames:
                  - glueops-core
              selector:
                matchLabels:
                  app.kubernetes.io/name: argocd-metrics
                  app.kubernetes.io/instance: argocd
                  app.kubernetes.io/component: application-controller
          - |-
            apiVersion: monitoring.coreos.com/v1
            kind: ServiceMonitor
            metadata:
              name: argocd-applicationset-controller
            spec:
              endpoints:
                - port: http-metrics
                  interval: 30s
                  path: /metrics
              namespaceSelector:
                matchNames:
                  - glueops-core
              selector:
                matchLabels:
                  app.kubernetes.io/name: argocd-metrics
                  app.kubernetes.io/instance: argocd
                  app.kubernetes.io/component: applicationset-controller
          - |-
            apiVersion: monitoring.coreos.com/v1
            kind: ServiceMonitor
            metadata:
              name: argocd-notifications-controller
            spec:
              endpoints:
                - port: http-metrics
                  path: /metrics
              namespaceSelector:
                matchNames:
                  - glueops-core
              selector:
                matchLabels:
                  app.kubernetes.io/name: argocd-metrics
                  app.kubernetes.io/instance: argocd
                  app.kubernetes.io/component: notifications-controller
          - |-
            apiVersion: monitoring.coreos.com/v1
            kind: ServiceMonitor
            metadata:
              name: argocd-repo-server
            spec:
              endpoints:
                - port: http-metrics
                  interval: 30s
                  path: /metrics
              namespaceSelector:
                matchNames:
                  - glueops-core
              selector:
                matchLabels:
                  app.kubernetes.io/name: argocd-repo-server-metrics
                  app.kubernetes.io/instance: argocd
                  app.kubernetes.io/component: repo-server
          - |-
            apiVersion: monitoring.coreos.com/v1
            kind: ServiceMonitor
            metadata:
              name: argocd-server
            spec:
              endpoints:
                - port: http-metrics
                  interval: 30s
                  path: /metrics
              namespaceSelector:
                matchNames:
                  - glueops-core
              selector:
                matchLabels:
                  app.kubernetes.io/name: argocd-server-metrics
                  app.kubernetes.io/instance: argocd
                  app.kubernetes.io/component: server
