apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glueops-vault-init-controller
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core-vault
  project: glueops-core
  syncPolicy:
    syncOptions:
      - Replace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - '.spec.template.spec.containers[].env[] | select(.name == "RESTORE_THIS_BACKUP") | .value'
  source:
    repoURL: https://helm.gpkg.io/project-template
    chart: app
    targetRevision: 0.6.0
    helm:
      values: |
        appName: 'vault-init-controller'
        image:
          registry: {{ .Values.container_images.app_vault_init_controller.vault_init_controller.image.registry }}
          repository: {{ .Values.container_images.app_vault_init_controller.vault_init_controller.image.repository }}
          tag: {{ .Values.container_images.app_vault_init_controller.vault_init_controller.image.tag }}
        serviceAccount:
          create: true
          name: vault-init-controller
        customResources:
          - |-
            apiVersion: rbac.authorization.k8s.io/v1
            kind: Role
            metadata:
              name: vault-init-controller
            rules:
            - apiGroups: [""]
              resources: ["pods"]
              verbs: ["get", "list", "watch"]
          - |-
            apiVersion: rbac.authorization.k8s.io/v1
            kind: RoleBinding
            metadata:
              name: vault-init-controller
            subjects:
            - kind: ServiceAccount
              name: vault-init-controller
              namespace: glueops-core-vault
            roleRef:
              kind: Role
              name: vault-init-controller
              apiGroup: rbac.authorization.k8s.io
        deployment:
          {{- toYaml .Values.glueops_node_and_tolerations | nindent 10 }}
          serviceAccount:
            enabled: true
            name: vault-init-controller
          replicas: 1
          enabled: true
          imagePullPolicy: IfNotPresent
          envVariables:
          - name: VAULT_S3_BUCKET
            value: "{{ .Values.vault_init_controller.s3_bucket_name }}"
          - name: VAULT_SECRET_FILE
            value: "{{ .Values.vault_init_controller.s3_key_path }}"
          - name: RECONCILE_PERIOD
            value: "{{ .Values.vault_init_controller.reconcile_period }}"
          - name: AWS_ACCESS_KEY_ID
            value: "{{ .Values.vault_init_controller.aws_accessKey }}"
          - name: AWS_SECRET_ACCESS_KEY
            value: "{{ .Values.vault_init_controller.aws_secretKey }}"
          - name: AWS_DEFAULT_REGION
            value: "{{ .Values.vault_init_controller.aws_region }}"
          - name: PAUSE_RECONCILE
            value: "{{ .Values.vault_init_controller.pause_reconcile }}"
          - name: ENABLE_RESTORE
            value: "{{ .Values.vault_init_controller.enable_restore }}"
          - name: CAPTAIN_DOMAIN
            value: "{{ .Values.captain_domain }}"
          - name: BACKUP_PREFIX
            value: "backups_with_expiration_enabled/hashicorp-vault-backups"
          - name: RESTORE_THIS_BACKUP
            value: ""
