apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core-promtail
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: promtail
    targetRevision: 6.11.2
    helm:
      parameters:
        - name: config.clients[0].url
          value: http://loki-write.glueops-core-loki.svc.cluster.local:3100/loki/api/v1/push
