apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glueops-descheduler
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: kube-system
  project: glueops-core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
  source:
    repoURL: 'https://github.com/kubernetes-sigs/descheduler.git'
    path: charts/descheduler
    targetRevision: v0.36.0
    helm:
      parameters:
        - name: kind
          value: "Deployment"
        - name: replicas
          value: "1"
        - name: image.repository
          value: "{{ .Values.container_images.app_descheduler.descheduler.image.registry }}/{{ .Values.container_images.app_descheduler.descheduler.image.repository }}"
        - name: image.tag
          value: "{{ .Values.container_images.app_descheduler.descheduler.image.tag }}"
      values: |-
         {{- toYaml .Values.glueops_node_and_tolerations | nindent 8 }}
        deschedulerPolicy:
          profiles:
            - name: default
              pluginConfig:
                - name: DefaultEvictor
                  args:
                    podProtections:
                      defaultDisabled:
                      - "PodsWithLocalStorage"
                      extraEnabled:
                      - "PodsWithPVC"
                    minReplicas: 2
                    noEvictionPolicy: "Mandatory"
                - name: RemovePodsHavingTooManyRestarts
                  args:
                    podRestartThreshold: 100
                    includingInitContainers: true
                - name: RemovePodsViolatingNodeAffinity
                  args:
                    nodeAffinityType:
                    - requiredDuringSchedulingIgnoredDuringExecution
                - name: RemovePodsViolatingNodeTaints
                - name: RemovePodsViolatingInterPodAntiAffinity
                - name: RemovePodsViolatingTopologySpreadConstraint
                - name: LowNodeUtilization
                  args:
                    thresholds:
                      cpu: 20
                      memory: 20
                      pods: 20
                    targetThresholds:
                      cpu: 50
                      memory: 50
                      pods: 50
              plugins:
                balance:
                  enabled:
                    - RemovePodsViolatingTopologySpreadConstraint
                    - LowNodeUtilization
                deschedule:
                  enabled:
                    - RemovePodsHavingTooManyRestarts
                    - RemovePodsViolatingNodeTaints
                    - RemovePodsViolatingNodeAffinity
                    - RemovePodsViolatingInterPodAntiAffinity