apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core-promtail
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: promtail
    targetRevision: 6.15.1
    helm:
      parameters:
        - name: config.clients[0].url
          value: http://loki-write.glueops-core-loki.svc.cluster.local:3100/loki/api/v1/push
      values: |-
        image:
          tag: 2.9.2
        tolerations:
          {{- toYaml .Values.glueops_node_and_tolerations.tolerations | nindent 10 }}
        config:
          snippets:
            extraScrapeConfigs: |
              - job_name: glueops-nginx-with-host
                pipeline_stages:
                  - cri: {}
                  - json:
                      expressions:
                        http_host: http_host
                  - labels:
                      http_host: http_host
                kubernetes_sd_configs:
                  - role: pod
                relabel_configs:
                  - source_labels:
                      - __meta_kubernetes_pod_controller_name
                    regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
                    action: replace
                    target_label: __tmp_controller_name
                  - source_labels:
                      - __meta_kubernetes_pod_label_app_kubernetes_io_name
                      - __meta_kubernetes_pod_label_app
                      - __tmp_controller_name
                      - __meta_kubernetes_pod_name
                    regex: ^;*([^;]+)(;.*)?$
                    action: replace
                    target_label: app
                  - source_labels:
                      - __meta_kubernetes_pod_label_app_kubernetes_io_instance
                      - __meta_kubernetes_pod_label_release
                    regex: ^;*([^;]+)(;.*)?$
                    action: replace
                    target_label: instance
                  - source_labels:
                      - __meta_kubernetes_pod_label_app_kubernetes_io_component
                      - __meta_kubernetes_pod_label_component
                    regex: ^;*([^;]+)(;.*)?$
                    action: replace
                    target_label: component
                  - action: replace
                    source_labels:
                    - __meta_kubernetes_pod_node_name
                    target_label: node_name
                  - action: replace
                    source_labels:
                    - __meta_kubernetes_namespace
                    target_label: namespace
                  - action: replace
                    replacement: $1
                    separator: /
                    source_labels:
                    - namespace
                    - app
                    target_label: job
                  - action: replace
                    source_labels:
                    - __meta_kubernetes_pod_name
                    target_label: pod
                  - action: replace
                    source_labels:
                    - __meta_kubernetes_pod_container_name
                    target_label: container
                  - action: replace
                    replacement: /var/log/pods/*nginx-controller*/*/*.log
                    separator: /
                    source_labels:
                    - __meta_kubernetes_pod_uid
                    - __meta_kubernetes_pod_container_name
                    target_label: __path__
                  - action: replace
                    regex: true/(.*)
                    replacement: /var/log/pods/*nginx-controller*/*/*.log
                    separator: /
                    source_labels:
                    - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
                    - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
                    - __meta_kubernetes_pod_container_name
                    target_label: __path__
                  - action: replace
                    target_label: glueops_job_name
                    replacement: nginx-with-host
                  - action: keep
                    source_labels:
                    - __meta_kubernetes_pod_name
                    regex: ".*nginx-controller.*"
