apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glueops-pomerium
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: pomerium
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
  source:
    repoURL: https://github.com/GlueOps/platform-kustomize-pomerium.git
    path: .
    targetRevision: v0.9.1
    kustomize:
      patches:
        - target:
            kind: Service
            name: pomerium-proxy
          patch: |-
            - op: add
              path: /metadata/annotations/chisel-operator.io/proxy-protocol
              value: "true"