apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metacontroller
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core-metacontroller
  project: glueops-core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    syncOptions:
      - Replace=true
      - CreateNamespace=true
  source:
    repoURL: 'https://helm.gpkg.io/platform'
    chart: metacontroller-helm
    targetRevision: v4.11.7
    helm:
      parameters:
        - name: replicas
          value: '2'
      values: |-
        {{- toYaml .Values.glueops_node_and_tolerations | nindent 8 }}

        commandArgs:
          - --zap-log-level=4
          - --discovery-interval=20s
          - --cache-flush-interval=30m
          - --health-probe-bind-address=:8081
          - --client-go-qps=150
          - --client-go-burst=300
          - --workers=50
