apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glueops-pomerium-post-deploy
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    name: "in-cluster"
    namespace: pomerium
  project: glueops-core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
  source:
    repoURL: 'https://helm.gpkg.io/platform'
    chart: glueops-pomerium-post-deploy
    targetRevision: 0.1.0
    helm:
      skipCrds: true
      parameters:
        - name: dex_domain
          value: dex.{{ .Values.captain_domain }}
        - name: pomerium_domain
          value: authenticated.{{ .Values.captain_domain }}
        - name: ingress_cert_name
          value: {{ .Values.certManager.name_of_default_certificate }}
        - name: client_id
          value: pomerium
        - name: client_secret
          value: {{ .Values.dex.pomerium.client_secret }}
