apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backup-hashicorp-vault
  annotations:
    argocd.argoproj.io/sync-wave: "100"  
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core-backup
  project: glueops-core
  source:
    chart: glueops-backup-hashicorp-vault
    helm:
      parameters:
      - name: aws_region
        value: "{{ .Values.glueops_backups.vault.aws_region }}"
      - name: aws_accessKey
        value: "{{ .Values.glueops_backups.vault.aws_accessKey }}"
      - name: aws_secretKey
        value: "{{ .Values.glueops_backups.vault.aws_secretKey }}"
      - name: captain_domain
        value: "{{ .Values.captain_domain }}"
      - name: company_key
        value: "{{ .Values.glueops_backups.vault.company_key }}"
      - name: cron_expression
        value: "{{ .Values.glueops_backups.vault.cron_expression }}"
    repoURL: https://helm.gpkg.io/platform
    targetRevision: 0.2.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    syncOptions:
    - CreateNamespace=true
