apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glueops-alerts
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core-alerts
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
      - Replace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
  source:
    path: ''
    repoURL: 'https://helm.gpkg.io/platform'
    targetRevision: 0.1.0
    helm:
      skipCrds: true
    chart: glueops-alerts
  project: glueops-core
