apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glueops-backups-and-exports
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core-backup
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
  source:
    repoURL: https://helm.gpkg.io/project-template
    chart: app
    targetRevision: 0.4.0
    helm:
      values: |+
        appName: "glueops-backup-and-exports"

      
        serviceAccount:
          create: true
          name: vault-backup

      
        cronJob:
          enabled: true
          jobs:
            vault-backups-to-s3:
              {{- toYaml .Values.glueops_node_and_tolerations | nindent 14 }}
              serviceAccount:
                enabled: true
                name: vault-backup
              schedule: "{{ .Values.glueops_backups.vault.cron_expression }}"
              concurrencyPolicy: Forbid
              successfulJobsHistoryLimit: 10
              failedJobsHistoryLimit: 3
              image: ghcr.io/glueops/backup-tools:v0.7.2
              command: ["/bin/bash", "-c"]
              args:
                - backup-vault
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
              envVariables:
                - name: AWS_ACCESS_KEY_ID
                  value: "{{ .Values.glueops_backups.vault.aws_accessKey }}"
                - name: AWS_SECRET_ACCESS_KEY
                  value: "{{ .Values.glueops_backups.vault.aws_secretKey }}"
                - name: AWS_DEFAULT_REGION
                  value: "{{ .Values.glueops_backups.vault.aws_region }}"
                - name: CAPTAIN_DOMAIN
                  value: "{{ .Values.captain_domain }}"
                - name: S3_BUCKET_NAME
                  value: "{{ .Values.glueops_backups.s3_bucket_name }}"
                - name: VAULT_ADDR
                  value: "https://vault-active.glueops-core-vault.svc.cluster.local:8200"
              volumeMounts:
                - mountPath: /app
                  name: vault-backups
              volumes:
              - name: vault-backups
                emptyDir:
                  medium: "" # Set to "Memory" for tmpfs (RAM-backed filesystem), or leave empty for node's filesystem
                  sizeLimit: 20G # Set the desired size limit
            loki-log-exporter-to-s3:
              {{- toYaml .Values.glueops_node_and_tolerations | nindent 14 }}
              schedule: "{{ .Values.glueops_backups.loki_exporter_to_s3.cron_expression }}"
              concurrencyPolicy: Forbid
              successfulJobsHistoryLimit: 10
              failedJobsHistoryLimit: 3
              image: ghcr.io/glueops/backup-tools:v0.7.2
              command: ["/bin/bash", "-c"]
              args:
                - backup-loki-logs-as-json
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
              envVariables:
                - name: AWS_ACCESS_KEY_ID
                  value: "{{ .Values.glueops_backups.loki_exporter_to_s3.aws_accessKey }}"
                - name: AWS_SECRET_ACCESS_KEY
                  value: "{{ .Values.glueops_backups.loki_exporter_to_s3.aws_secretKey }}"
                - name: AWS_DEFAULT_REGION
                  value: "{{ .Values.glueops_backups.loki_exporter_to_s3.aws_region }}"
                - name: CAPTAIN_DOMAIN
                  value: "{{ .Values.captain_domain }}"
                - name: S3_BUCKET_NAME
                  value: "{{ .Values.glueops_backups.s3_bucket_name }}"
                - name: LOKI_ADDR
                  value: "http://loki-gateway.glueops-core-loki.svc.cluster.local"
              volumeMounts:
                - mountPath: /app
                  name: loki-log-exports
              volumes:
              - name: loki-log-exports
                emptyDir:
                  medium: "" # Set to "Memory" for tmpfs (RAM-backed filesystem), or leave empty for node's filesystem
                  sizeLimit: 20G # Set the desired size limit
