apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glueops-pull-request-bot
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core-pull-request-bot
  source:
    path: ''
    repoURL: 'https://helm.gpkg.io/platform'
    targetRevision: 0.2.0
    chart: glueops-pull-request-bot
  project: glueops-core
  syncPolicy:
    syncOptions:
      - Replace=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
      limit: 2
