apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core-external-secrets
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
  source:
    repoURL: 'https://helm.gpkg.io/platform'
    chart: glueops-external-secrets
    targetRevision: 0.6.3
    helm:
      skipCrds: true
      parameters:
        - name: external-secrets.webhook.hostNetwork
          value: "{{ .Values.host_network.enabled }}"
        - name: external-secrets.webhook.port
          value: "{{ .Values.host_network.external_secrets.webhook_port }}"
      values: |
        external-secrets:
          {{- toYaml .Values.glueops_node_and_tolerations | nindent 10 }}
          webhook:
            {{- toYaml .Values.glueops_node_and_tolerations | nindent 12 }}
          certController:
            {{- toYaml .Values.glueops_node_and_tolerations | nindent 12 }}
