apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-alert-group-controller
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core-loki-alert-group-controller
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
      limit: 2
  source:
    repoURL: https://helm.gpkg.io/project-template
    chart: app
    targetRevision: 0.3.0
    helm:
      values: |
        appName: '{{ .Release.Name }}'
        image:
          registry: ghcr.io
          repository: glueops/metacontroller-operator-loki-rule-group
          tag: v0.2.5
          pullPolicy: IfNotPresent

        service:
          enabled: true
          port: 80

        app:
          port: 80
        deployment:
          envVariables:
            - name: LOKI_API_ENDPOINT
              value: 'http://loki-gateway.glueops-core-loki.svc.cluster.local'
          {{- toYaml .Values.glueops_node_and_tolerations | nindent 10 }}
          replicas: 2
          enabled: true
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 128Mi


        customResources:
          - |-
            apiVersion: apiextensions.k8s.io/v1
            kind: CustomResourceDefinition
            metadata:
              name: lokialertrulegroups.metacontroller.glueops.dev
            spec:
              group: metacontroller.glueops.dev
              names:
                kind: LokiAlertRuleGroup
                listKind: LokiAlertRuleGroupList
                plural: lokialertrulegroups
                singular: lokialertrulegroup
              scope: Namespaced
              versions:
                - name: v1alpha1
                  served: true
                  storage: true
                  schema:
                    openAPIV3Schema:
                      type: object
                      properties:
                        spec:
                          type: object
                          properties:
                            name:
                              type: string
                            rules:
                              type: array
                              items:
                                type: object
                                properties:
                                  alert:
                                    type: string
                                  expr:
                                    type: string
                                  for:
                                    type: string
                                  labels:
                                    type: object
                                    additionalProperties:
                                      type: string
                                  annotations:
                                    type: object
                                    additionalProperties:
                                      type: string
                        status:
                          type: object
                          properties:
                            health:
                              type: object
                              properties:
                                status:
                                  type: string
                  subresources:
                   status: {}



          - |-
            apiVersion: metacontroller.k8s.io/v1alpha1
            kind: CompositeController
            metadata:
              name: {{ .Release.Name }}
            spec:
              generateSelector: true
              parentResource:
                apiVersion: metacontroller.glueops.dev/v1alpha1
                resource: lokialertrulegroups
              childResources:
                - apiVersion: v1
                  resource: configmaps
                  updateStrategy:
                    method: InPlace
              resyncPeriodSeconds: 30
              hooks:
                sync:
                  webhook:
                    url: http://{{ .Release.Name }}.glueops-core-loki-alert-group-controller.svc.cluster.local
                finalize:
                  webhook:
                    url: http://{{ .Release.Name }}.glueops-core-loki-alert-group-controller.svc.cluster.local/finalize
        