apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-alert-group-controller
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core-loki-alert-group-controller
  source:
    path: ''
    repoURL: 'https://incubating-helm.gpkg.io/platform'
    targetRevision: v0.1.0-alpha6
    helm:
      parameters:
        - name: loki-alert-group-controller.replicaCount
          value: {{ .Values.lokiAlertGroupController.replica_count }}
        - name: loki-alert-group-controller.image.pullPolicy
          value: {{ .Values.lokiAlertGroupController.image.pull_policy}}
        - name: loki-alert-group-controller.image.tag
          value: {{ .Values.lokiAlertGroupController.image.tag}}
        - name: loki-alert-group-controller.image.lokiGatewayUrl
          value: {{ .Values.lokiAlertGroupController.image.loki_gateway_url}}
    chart: platform-helm-chart-metacontroller-operator-loki-rule-group
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
      limit: 2
