apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glueops-pomerium
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: pomerium
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
  source:
    repoURL: https://github.com/pomerium/ingress-controller.git
    path: config/default
    targetRevision: v0.27.2
    kustomize:
      patches:
        - target:
            kind: Service
            name: pomerium-proxy
          patch: |-
            - op: add
              path: /metadata/annotations/chisel-operator.io~1proxy-protocol
              value: "false"
        - target:
            kind: Deployment
            name: pomerium
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/imagePullPolicy
              value: "IfNotPresent"

            - op: replace
              path: /spec/template/spec/containers/0/image
              value: {{ .Values.base_registry }}/{{ .Values.container_images.app_pomerium.pomerium_deployment.image.repository }}:{{ .Values.container_images.app_pomerium.pomerium_deployment.image.tag }}
              

            - op: replace
              path: /spec/template/spec/containers/0/resources
              value:
                limits:
                  cpu: 5
                  memory: 4Gi
                requests:
                  cpu: 300m
                  memory: 200Mi

            - op: replace
              path: /spec/template/spec/nodeSelector
              value:
                glueops.dev/role: "glueops-platform"

            - op: replace
              path: /spec/template/spec/tolerations
              value:
                - key: "glueops.dev/role"
                  operator: "Equal"
                  value: "glueops-platform"
                  effect: "NoSchedule"
        - target:
            kind: Job
            name: pomerium-gen-secrets
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/image
              value: {{ .Values.base_registry }}/{{ .Values.container_images.app_pomerium.pomerium_job.image.repository }}:{{ .Values.container_images.app_pomerium.pomerium_job.image.tag }}

            - op: replace
              path: /spec/template/spec/containers/0/imagePullPolicy
              value: "IfNotPresent"