apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core-external-secrets
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
  source:
    repoURL: 'https://github.com/GlueOps/platform-helm-chart-external-secrets'
    path: .
    targetRevision: v0.8.0
    helm:
      skipCrds: true
      parameters:
        - name: external-secrets.webhook.hostNetwork
          value: "{{ .Values.host_network.enabled }}"
        - name: external-secrets.webhook.port
          value: "{{ .Values.host_network.external_secrets.webhook_port }}"
        - name: external-secrets.webhook.metrics.listen.port
          value: "{{ .Values.host_network.external_secrets.webhook_metrics_port }}"
        - name: external-secrets.webhook.metrics.service.port
          value: "{{ .Values.host_network.external_secrets.webhook_metrics_port }}"
        - name: external-secrets.image.repository
          value: "{{ .Values.container_images.app_external_secrets.external_secrets.image.registry }}/{{ .Values.container_images.app_external_secrets.external_secrets.image.repository }}"
        - name: external-secrets.image.tag
          value: "{{ .Values.container_images.app_external_secrets.external_secrets.image.tag }}"
        - name: external-secrets.webhook.image.repository
          value: "{{ .Values.container_images.app_external_secrets.external_secrets.image.registry }}/{{ .Values.container_images.app_external_secrets.external_secrets.image.repository }}"
        - name: external-secrets.webhook.image.tag
          value: "{{ .Values.container_images.app_external_secrets.external_secrets.image.tag }}"
        - name: external-secrets.certController.image.repository
          value: "{{ .Values.container_images.app_external_secrets.external_secrets.image.registry }}/{{ .Values.container_images.app_external_secrets.external_secrets.image.repository }}"
        - name: external-secrets.certController.image.tag
          value: "{{ .Values.container_images.app_external_secrets.external_secrets.image.tag }}"
      values: |
        external-secrets:
          {{- toYaml .Values.glueops_node_and_tolerations | nindent 10 }}
          webhook:
            {{- toYaml .Values.glueops_node_and_tolerations | nindent 12 }}
          certController:
            {{- toYaml .Values.glueops_node_and_tolerations | nindent 12 }}
