apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-thanos-stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core-kube-prometheus-stack
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: thanos
    targetRevision: 15.7.25
    helm:
      skipCrds: true
      values: |-
        objstoreConfig: |-
          type: s3
          config:
            bucket: {{ .Values.thanos.bucket}}
            endpoint: s3.{{ .Values.thanos.aws_region }}.amazonaws.com
            access_key: '{{ .Values.thanos.aws_accessKey }}'
            secret_key: '{{ .Values.thanos.aws_secretKey }}'
          prefix: '{{ .Values.thanos.prefix }}'    
        query:
          dnsDiscovery:
            enabled: true
            logLevel: debug
            sidecarsService: "kps-thanos-discovery"
            sidecarsNamespace: "glueops-core-kube-prometheus-stack"
        bucketweb:
          enabled: true
        compactor:
          enabled: true
        storegateway:
          enabled: true    