apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core-otel
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
  source:
    repoURL: 'https://open-telemetry.github.io/opentelemetry-helm-charts'
    chart: opentelemetry-operator
    targetRevision: 0.87.0
    helm:
      skipCrds: true
      values: |-
        replicaCount: {{ .Values.otel.replicas }}
        nameOverride: {{ .Values.otel.name_override }}
        manager:
           {{- toYaml .Values.otel.manager | nindent 12 }}