apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glueops-qr-code-generator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core-qr-code-generator
  project: glueops-core
  syncPolicy:
    syncOptions:
      - Replace=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        maxDuration: 3m0s
        factor: 2
      limit: 5
  source:
    repoURL: 'https://helm.gpkg.io/project-template'
    chart: app
    targetRevision: 0.4.0
    helm:
      values: |-
        appName: 'qr-code-generator'
        replicaCount: '2'
        image: 
          registry: ghcr.io
          repository: glueops/qr-code-generator
          tag: v0.2.7
          pullPolicy: IfNotPresent
          port: 8000
                
        deployment: 
          enabled: true
          {{- toYaml .Values.glueops_node_and_tolerations | nindent 10 }}

        service:
          enabled: true
          type: ClusterIP
          ports: 
            - port: 80
              name: qr-code-generator
              protocol: TCP
              targetPort: 8000

        ingress:
          enabled: true
          ingressClassName: public
          entries:
            - name: public
              hosts:
                - hostname: qr-code-generator.{{ .Values.captain_domain }}
                  paths:
                    - path: /
                      pathType: Prefix
                      servicePortNumber: 80
       
