apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-thanos-stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "in-cluster"
    namespace: glueops-core-kube-prometheus-stack
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: thanos
    targetRevision: 15.7.25
    helm:
      skipCrds: true
      values: |-
        objstoreConfig:
        {{- toYaml .Values.thanos.storage | nindent 12 }}
        query:
          replicaLabel: ["__replica__"]
          resources: 
            requests:
              cpu: 2
              memory: 1024Mi
            limits:
               cpu: 3
               memory: 2024Mi
          dnsDiscovery:
            enabled: true
            logLevel: debug
            sidecarsService: "kps-thanos-discovery"
            sidecarsNamespace: "glueops-core-kube-prometheus-stack"
        bucketweb:
          enabled: true
        compactor:
          enabled: true
          retentionResolutionRaw: 15d
          retentionResolution5m: 30d
          retentionResolution1h: 10y
          resources:
            requests:
              cpu: 2
              memory: 512Mi
            limits:
               cpu: 3
               memory: 2024Mi
        storegateway:
          enabled: true
          useEndpointGroup: true