apiVersion: v1
kind: ConfigMap
metadata:
  name: glueops-captain-domain
data:
  captain_domain: {{ .Values.captain_domain }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: tenant-repo-creds
  labels:
    argocd.argoproj.io/instance: argo-cd
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
  url: https://github.com/{{ .Values.gitHub.tenant_github_org }}
  githubAppID: "{{ .Values.gitHub.github_app_id }}"
  githubAppInstallationID: "{{ .Values.gitHub.github_app_installation_id }}"
data:
  githubAppPrivateKey: {{ .Values.gitHub.github_app_b64enc_private_key }}
---
