
{{- if .Values.externalSecretsExampleEnabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-db-password
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: example-openbao
    kind: ClusterSecretStore
  target:
    name: db-password
    creationPolicy: Owner
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: kv/data/myapp          # KV v2 example
      property: DB_PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: example-openbao
spec:
  provider:
    vault:
      server: {{ include "secretsProvider.server" . | quote }}
      path: "kv"
      version: "v2"
      {{- if eq .Values.secretsProvider.auth.type "kubernetes" }}
      auth:
        kubernetes:
          mountPath: {{ .Values.secretsProvider.auth.kubernetes.mount | default "kubernetes" | quote }}
          role: {{ .Values.secretsProvider.auth.kubernetes.role | quote }}
      {{- else if eq .Values.secretsProvider.auth.type "approle" }}
      auth:
        appRole:
          path: "approle"
          roleId: {{ .Values.secretsProvider.auth.approle.roleId | quote }}
          secretRef:
            name: {{ .Values.secretsProvider.auth.approle.secretIdRef | quote }}
            key: secretId
      {{- else if eq .Values.secretsProvider.auth.type "token" }}
      auth:
        tokenSecretRef:
          name: {{ .Values.secretsProvider.auth.token.valueFromSecret | quote }}
          key: token
      {{- end }}
      caBundle: |
        {{- if .Values.secretsProvider.caBundle.inlinePEM -}}
{{ .Values.secretsProvider.caBundle.inlinePEM | nindent 8 }}
        {{- end -}}
{{- end }}
