apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: glueops-core
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
