
{{- if and .Values.secretsProvider.caBundle.inlinePEM (not .Values.secretsProvider.caBundle.secretRef) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: sp-ca
  namespace: {{ .Values.argocd.namespace | default "argocd" }}
data:
  ca.pem: |
{{ .Values.secretsProvider.caBundle.inlinePEM | indent 4 }}
{{- end }}
