apiVersion: v1
kind: ServiceAccount
metadata:
  name: qr-secrets-bootstrap
  namespace: glueops-core
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: qr-secrets-bootstrap
rules:
  - apiGroups: [""]
    resources: ["secrets", "namespaces"]
    verbs: ["get", "list", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: qr-secrets-bootstrap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: qr-secrets-bootstrap
subjects:
  - kind: ServiceAccount
    name: qr-secrets-bootstrap
    namespace: glueops-core
---
apiVersion: batch/v1
kind: Job
metadata:
  name: qr-secrets-bootstrap
  namespace: glueops-core
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-10"
    argocd.argoproj.io/sync-wave: "-10"
spec:
  backoffLimit: 2
  template:
    spec:
      serviceAccountName: qr-secrets-bootstrap
      restartPolicy: Never
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command: ["/bin/sh","-c"]
          env:
            - name: NS_BOT
              value: glueops-core-pull-request-bot
            - name: NS_QR
              value: glueops-core-qr-code-generator
            - name: SECRET_NAME
              value: qr-shared
          args:
            - |
              set -euo pipefail

              can_access_ns () {
                kubectl -n "$1" get secret >/dev/null 2>&1
              }

              echo "Checking whether we can access target namespaces..."
              BOT_OK=0
              QR_OK=0
              can_access_ns "$NS_BOT" && BOT_OK=1
              can_access_ns "$NS_QR" && QR_OK=1

              if [ "$BOT_OK" -eq 0 ] && [ "$QR_OK" -eq 0 ]; then
                echo "Cannot access $NS_BOT or $NS_QR yet (namespace may not exist); exiting successfully."
                exit 0
              fi

              echo "Getting existing QR_MINT_TOKEN (prefer $NS_BOT, fallback $NS_QR)..."
              MINT=""
              
              if [ "$BOT_OK" -eq 1 ]; then
                MINT="$(kubectl -n "$NS_BOT" get secret "$SECRET_NAME" -o jsonpath='{.data.QR_MINT_TOKEN}' 2>/dev/null | base64 -d || true)"
              fi
              if [ -z "${MINT}" ] && [ "$QR_OK" -eq 1 ]; then
                MINT="$(kubectl -n "$NS_QR" get secret "$SECRET_NAME" -o jsonpath='{.data.QR_MINT_TOKEN}' 2>/dev/null | base64 -d || true)"
              fi

              if [ -z "${MINT}" ]; then
                echo "No existing QR_MINT_TOKEN found; generating..."
                MINT="$(head -c 32 /dev/urandom | base64 | tr -d '\n')"
              else
                echo "Found existing QR_MINT_TOKEN; reusing."
              fi

              echo "Ensuring QR_SIGNING_SECRET exists (only used in $NS_QR)..."
              SIGN=""
              if [ "$QR_OK" -eq 1 ]; then
                SIGN="$(kubectl -n "$NS_QR" get secret "$SECRET_NAME" -o jsonpath='{.data.QR_SIGNING_SECRET}' 2>/dev/null | base64 -d || true)"
              fi
              if [ -z "${SIGN}" ]; then
                echo "No existing QR_SIGNING_SECRET found; generating..."
                SIGN="$(head -c 32 /dev/urandom | base64 | tr -d '\n')"
              else
                echo "Found existing QR_SIGNING_SECRET; reusing."
              fi

              echo "Applying secrets..."
              if [ "$BOT_OK" -eq 1 ]; then
                kubectl -n "$NS_BOT" create secret generic "$SECRET_NAME" \
                  --from-literal=QR_MINT_TOKEN="$MINT" \
                  --dry-run=client -o yaml | kubectl apply -f -
              else
                echo "Skipping $NS_BOT (cannot access)."
              fi

              if [ "$QR_OK" -eq 1 ]; then
                kubectl -n "$NS_QR" create secret generic "$SECRET_NAME" \
                  --from-literal=QR_MINT_TOKEN="$MINT" \
                  --from-literal=QR_SIGNING_SECRET="$SIGN" \
                  --dry-run=client -o yaml | kubectl apply -f -
              else
                echo "Skipping $NS_QR (cannot access)."
              fi

              echo "Done."
