name: Update Docs
on:
  push:


jobs:
  call-workflow-passing-data:
    uses: GlueOps/github-workflows/.github/workflows/helm-docs.yml@536dd7ba5e206a5a9ba4c01b0b5fc15aa5f5690a # main
    secrets: inherit
    
